### ISSUE TITLE
readme.txt files in multi-file download bundles

### ISSUE THREAD

**Issue by pli888** [rija/gigadb-website#12]
Not sure if its just me but I'm having problems with getting readme.txt files being incorporated into bundles.

For example, in this [dataset](http://127.0.0.1:9170/dataset/view/id/100117/) can you try downloading contributors.txt, README.md and readme.txt files as a bundle?  The downloaded bundle only contains contributors.txt and README.md for me.

**Comment by rija** [comment]
Hi Peter, 

this is expected behaviour as the provisioning process only install a subset of the files for the dataset from the production like database.

the list of files installed are listed here:

https://github.com/rija/gigadb-website/blob/ftp-table/SETUP.md
